### ISSUE TITLE
:xml parsing should not lowercase tags

### ISSUE THREAD

**Issue by terjesb** [Raynes/laser#25]
Was about to try Laser for some "inline" SOAP stuff. However:

``` clojure
(l/document (l/parse "<Test xmlns:Ex=\"yo\"/>" :xml))
=> "<test xmlns:ex=\"yo\"></test>"
```

XML is case-sensitive, so I had expected this to return:

``` clojure
"<Test xmlns:Ex=\"yo\"></Test>"
```

**Comment by Raynes** [comment]
That's interesting. I'll take a look and see what's going on in a bit.

**Comment by Raynes** [comment]
This is a problem in Jsoup itself I'm afraid. I'm going to open an issue there instead.
